# Project information
site_name: 'Ansible wiki'
site_description: 'ansible,wiki,ops,devops,auto,运维自动化'
site_author: 'lework'
site_url: 'https://ansible.leops.cn'

# Repository
repo_name: 'leops-china/ansible-wiki'
repo_url: 'https://github.com/leops-china/ansible-wiki'

# Copyright
copyright: 'Copyright &copy; 2020 - 2020 leops'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  features:
    - tabs
  palette:
    scheme: default
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: iso_datetime

# Customization
extra:
  utteranc:
    repo: leops-china/ansible-wiki
    issueTerm: pathname
    theme: github-light
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/leops-china/ansible-wiki'

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: leops-china
      repo: ansible-wiki
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed

nav:
  - 'Home': index.md
  - 'Ansible 资源': resources.md
  - '赞赏支持': appreciate.md
  - 'Ansible 入门': 
      - '1. Ansible 介绍': basic/Introduction.md
      - '2. 安装 Ansible': basic/Installation.md
      - '3. 快速开始': basic/Quickstart.md
      - '4. 认识主机清单': basic/Inventory.md
      - '5. Patterns 匹配': basic/Patterns.md
      - '6. 使用 ad-hoc 命令': basic/Ad-hoc.md
      - '7. 熟悉 ansible 命令': basic/Ansible-command.md
      - '8. 使用 Playbook': basic/Playbook.md
      - '9. 包含和角色': basic/Include-roles.md
      - '10. 使用变量': basic/Variables.md
      - '11. Facts 数据': basic/Facts.md
      - '12. Jinja2 模板语法': basic/Jinja2.md
      - '13. 条件判断与循环': basic/Conditionals-loop.md
      - '14. Blocks': basic/Blocks.md
      - '15. Playbook 高级特性': basic/Playbook-features.md
      - '扩展阅读(深入必读)':
         - '1. YAML 语法': basic/Reference/Yaml.md
         - '2. Vaults 加密数据': basic/Reference/Vaults.md
         - '3. 关键字使用': basic/Reference/Keywords.md
         - '4. 模块索引': basic/Reference/Module.md
         - '5. Ansible 配置': basic/Reference/Config.md
      - 'Windows':
         - '1. 管理 Windows 主机': basic/Windows/manager-windows.md
  - 'Ansible 进阶': 
     - 'Ansible 优化': advanced/optimization.md
     - 'Ansible 最佳实践': advanced/best-practices.md
     - '使用 Ansible-lint': advanced/ansible-lint.md
     - '使用动态主机': advanced/dynamic-hosts.md
     - '使用动态主机管理云服务': advanced/dynamic-inventory.md
     - 'Ansible 安全': 
        - 'Ansible 控制节点安全': advanced/security/index.md
        - '- 节点安全: 防火墙设置': advanced/security/firewall.md
        - '- 节点安全: ssh登录二次验证': advanced/security/ssh-2step.md
        - '- 节点安全: 命令审计': advanced/security/audit.md
        - '- 节点安全: 加密主机清单': advanced/security/vault-hosts.md
        - 过滤 Ansible 危险指令: advanced/security/filter-command.md
     - 'Ansible 实践':
        - 'Ansible Task片段': advanced/practice/snippets.md
        - '在 Jenkins 中使用 Ansible': advanced/practice/jenkins-and-ansible.md
     - '使用 ARA 记录 Ansible 执行结果': advanced/ara.md
     - '使用 Ansible-cmdb': advanced/ansible-cmdb.md
  - 'Ansible 开发':
     - 'Ansible 开发说明': dev/index.md
     - 'Ansible 架构': dev/ansible-architecture.md
     - '使用 PyCharm 远程开发': dev/pycharm-remote-development.md
     - 'Ansible 调试': 
        - '详细输出': dev/debug/verbose-debug.md
        - 'pdb 本地调试': dev/debug/pdb.md
        - 'PyCharm 远程调试': dev/debug/pycharm.md
        - '模块调试': dev/debug/module-debug.md
     - 'Module 开发':
        - 'Module 开发说明': dev/modules/index.md
        - '创建一个简单的module':  dev/modules/remote_copy.md
        - 'module 示例: 连接华为交换机':  dev/modules/huawei-switch.md
        - 'module 示例: 其他语言开发':  dev/modules/module-outher-dev.md
        - 'module 示例: docker_facts':  dev/modules/module-docker-facts.md
        - 'module 示例: wechat':  dev/modules/module-wechat.md
        - 'module 的返回值':  dev/modules/module-return.md
        - 'module 的帮助文档':  dev/modules/module-doc.md
        - 'module 架构':  dev/modules/module-architecture.md
        - 'module 工具类':  dev/modules/module-utilities.md
     - 'Plugin 开发':
        - 'Plugin 开发说明': dev/plugins/index.md
        - 'Action 示例: hello':  dev/plugins/Action-hello.md
        - 'Callback 示例: BlackHole':  dev/plugins/Callback-BlackHole.md
        - 'Filter 示例: split':  dev/plugins/Filter-split.md
        - 'Inventory 示例: csv':  dev/plugins/Inventory-csv.md
        - 'Lookup 示例: github_status':  dev/plugins/Lookup-github-status.md
        - 'Vars 示例: csv_vars':  dev/plugins/Vars-csv-vars.md
     - 'API 使用':
        - 'API 使用说明': dev/api/index.md
        - '使用 API 运行任务':  dev/api/api-task.md
        - '使用 API 运行 Palybook':  dev/api/api-playbook.md
        - '使用 suitable':  dev/api/api-suitable.md
        - '使用 ansible runner':  dev/api/api-ansible-runner.md
  - 'Ansible UI':
     - 'Ansible UI 说明': ui/index.md
     - 'Ansible Awx': ui/awx.md
     - 'Ansible Tower': ui/tower.md
  - 'Ansible 认证':
     - 'Ansible 认证说明': certification/index.md
     - 'EX407 示例试题': certification/ex407-example.md
  - 'Ansible Roles':
     - 'Ansible roles 怎么用？': roles/index.md
     - '认证':
        - kerberos-client: roles/auth/kerberos-client.md
        - kerberos-server: roles/auth/kerberos-server.md
        - openldap: roles/auth/openldap.md
     - '系统环境': 
        - ant: roles/env/ant.md
        - erlang: roles/env/erlang.md
        - go: roles/env/go.md
        - hostnames: roles/env/hostnames.md
        - java: roles/env/java.md
        - lua: roles/env/lua.md
        - mvn: roles/env/mvn.md
        - nodejs: roles/env/nodejs.md
        - openssh: roles/env/openssh.md
        - openssl: roles/env/openssl.md
        - os-init: roles/env/os-init.md
        - php: roles/env/php.md
        - python2.7: roles/env/python2.7.md
        - repo-epel: roles/env/repo-epel.md
        - ruby: roles/env/ruby.md
        - sbt: roles/env/sbt.md
        - ssh-2fa: roles/env/ssh-2fa.md
        - ssh-keys: roles/env/ssh-keys.md
        - update-kernel: roles/env/update-kernel.md
     - 'WEB':
        - nginx: roles/web/nginx.md
        - openresty: roles/web/openresty.md
        - tengine: roles/web/tengine.md
        - tomcat: roles/web/tomcat.md
     - '数据库':
        - memcached: roles/database/memcached.md
        - mongodb: roles/database/mongodb.md
        - mycat: roles/database/mycat.md
        - mysql: roles/database/mysql.md
        - mysql57: roles/database/mysql57.md
        - redis: roles/database/redis.md
        - redis5: roles/database/redis5.md
        - codis: roles/database/codis.md
     - '键值存储':
        - consul: roles/kv/consul.md
        - etcd: roles/kv/etcd.md
        - zookeeper: roles/kv/zookeeper.md
     - '大数据':
        - airflow: roles/bigdata/airflow.md
        - cdh5-agent: roles/bigdata/cdh5-agent.md
        - cdh5-pre: roles/bigdata/cdh5-pre.md
        - cdh5-server: roles/bigdata/cdh5-server.md
        - hadoop-standalone: roles/bigdata/hadoop-standalone.md
        - superset: roles/bigdata/superset.md
     - '消息系统':
        - kafka: roles/mq/kafka.md
        - kafka-manager: roles/mq/kafka-manager.md
        - rabbitmq: roles/mq/rabbitmq.md
     - '持续集成/交付':
        - deploy-image: roles/ci/deploy-image.md
        - deploy-static: roles/ci/deploy-static.md
        - deploy-supervisor: roles/ci/deploy-supervisor.md
        - deploy-tomcat: roles/ci/deploy-tomcat.md
        - jenkins: roles/ci/jenkins.md
        - nexus: roles/ci/nexus.md
     - '高可用':
        - keepalived: roles/ha/keepalived.md
     - '代理':
        - haproxy: roles/proxy/haproxy.md
     - '监控':
        - grafana: roles/monitor/grafana.md
        - zabbix-agent: roles/monitor/zabbix-agent.md
        - zabbix-server: roles/monitor/zabbix-server.md
     - '日志分析':
        - elasticsearch: roles/log/elasticsearch.md
        - filebeat: roles/log/filebeat.md
        - grokdebug: roles/log/grokdebug.md
        - kibana: roles/log/kibana.md
        - logstash: roles/log/logstash.md
     - '存储':
        - gluster: roles/storage/gluster.md
        - nfs: roles/storage/nfs.md
        - samba: roles/storage/samba.md
        - vsftpd: roles/storage/vsftpd.md
     - '容器':
        - docker-compose: roles/container/docker-compose.md
        - docker-swarm: roles/container/docker-swarm.md
        - docker: roles/container/docker.md
        - harbor: roles/container/harbor.md
        - kubernetes-bin: roles/container/kubernetes-bin.md
        - kubernetes: roles/container/kubernetes.md
        - shipyard: roles/container/shipyard.md
     - '数据同步':
        - rsync: roles/sync/rsync.md
        - sersync: roles/sync/sersync.md
     - '其他':
        - chrony: roles/other/chrony.md
        - confd: roles/other/confd.md
        - iptables: roles/other/iptables.md
        - ntp: roles/other/ntp.md
        - os-check: roles/other/os-check.md
        - supervisor: roles/other/supervisor.md